"""Static Kyiv restaurant catalogue."""

RESTAURANTS = [
    {"id": 1, "name": "Kanapa", "lat": 50.4547, "lng": 30.5238,
     "cuisine": "Українська", "address": "вул. Андріївський узвіз, 19",
     "url": "https://kanapa-restaurant.com.ua", "hours": [12, 23], "schedule": "all",
     "desc": "Відомий ресторан української кухні з автентичними стравами та стильним інтер'єром на Андріївському узвозі.",
     "desc_en": "Famous Ukrainian cuisine restaurant with authentic dishes and a stylish interior on Andriyivsky Uzviz.",
     "desc_ru": "Известный ресторан украинской кухни с аутентичными блюдами и стильным интерьером на Андреевском спуске."},
    {"id": 2, "name": "Osteria Pantagruel", "lat": 50.4530, "lng": 30.5201,
     "cuisine": "Італійська", "address": "вул. Lva Tolstoho, 1",
     "url": "https://pantagruel.ua", "hours": [12, 23], "schedule": "all",
     "desc": "Вишукана остерія з класичною італійською кухнею, свіжою пастою та великим вибором вин.",
     "desc_en": "Refined osteria with classic Italian cuisine, fresh pasta and an extensive wine selection.",
     "desc_ru": "Изысканная остерия с классической итальянской кухней, свежей пастой и большим выбором вин."},
    {"id": 3, "name": "Hutorok na Dnipri", "lat": 50.4602, "lng": 30.5180,
     "cuisine": "Українська", "address": "пров. Ланцюгова, 1",
     "url": "https://hutoroky.com.ua", "hours": [10, 22], "schedule": "all",
     "desc": "Затишний ресторан з видом на Дніпро, домашньою українською їжею та живою музикою у вихідні.",
     "desc_en": "Cozy restaurant with a Dnipro view, homestyle Ukrainian food and live music on weekends.",
     "desc_ru": "Уютный ресторан с видом на Днепр, домашней украинской едой и живой музыкой по выходным."},
    {"id": 4, "name": "The Burger", "lat": 50.4461, "lng": 30.5234,
     "cuisine": "Американська", "address": "вул. Baseina, 1/2",
     "url": "https://theburger.ua", "hours": [10, 22], "schedule": "all",
     "desc": "Культовий бургер-бар з крафтовими бургерами, хрусткою картоплею фрі та великим вибором крафтового пива.",
     "desc_en": "Cult burger bar with craft burgers, crispy fries and a wide selection of craft beer.",
     "desc_ru": "Культовый бургер-бар с крафтовыми бургерами, хрустящей картошкой фри и большим выбором крафтового пива."},
    {"id": 5, "name": "Tarantino Family", "lat": 50.4408, "lng": 30.5193,
     "cuisine": "Середземноморська", "address": "вул. Велика Васильківська, 55",
     "url": "https://tarantino.ua", "hours": [11, 23], "schedule": "all",
     "desc": "Сімейний ресторан середземноморської кухні з великою терасою, ідеальний для сімей із дітьми.",
     "desc_en": "Family Mediterranean restaurant with a large terrace, perfect for families with children.",
     "desc_ru": "Семейный ресторан средиземноморской кухни с большой террасой, идеальный для семей с детьми."},
    {"id": 6, "name": "Spotykach", "lat": 50.4476, "lng": 30.5153,
     "cuisine": "Українська", "address": "вул. Volodymyrska, 16",
     "url": "", "hours": [11, 22], "schedule": "all",
     "desc": "Демократичний ресторан традиційної української кухні у самому серці Києва, поруч із Золотими воротами.",
     "desc_en": "Affordable traditional Ukrainian restaurant in the heart of Kyiv, next to the Golden Gate.",
     "desc_ru": "Демократичный ресторан традиционной украинской кухни в самом центре Киева, рядом с Золотыми воротами."},
    {"id": 7, "name": "Сирна", "lat": 50.4519, "lng": 30.5236,
     "cuisine": "Українська", "address": "вул. Хрещатик, 27",
     "url": "", "hours": [9, 21], "schedule": "all",
     "desc": "Спеціалізований ресторан з понад 50 видами українських та імпортних сирів, фондю та сирними десертами.",
     "desc_en": "Specialty restaurant with over 50 types of Ukrainian and imported cheeses, fondue and cheese desserts.",
     "desc_ru": "Специализированный ресторан с более чем 50 видами украинских и импортных сыров, фондю и сырными десертами."},
    {"id": 8, "name": "Musafir", "lat": 50.4558, "lng": 30.5267,
     "cuisine": "Кримськотатарська", "address": "вул. Desiatynna, 11",
     "url": "", "hours": [12, 22], "schedule": "all",
     "desc": "Єдиний у Києві ресторан кримськотатарської кухні — чебуреки, лагман та манти у національному колориті.",
     "desc_en": "The only Crimean Tatar restaurant in Kyiv — chebureki, lagman and manti in authentic national style.",
     "desc_ru": "Единственный в Киеве ресторан крымскотатарской кухни — чебуреки, лагман и манты в национальном колорите."},
    {"id": 9, "name": "PapaJons", "lat": 50.4382, "lng": 30.5107,
     "cuisine": "Піца", "address": "вул. Chervonoarmijska, 4",
     "url": "", "hours": [10, 22], "schedule": "all",
     "desc": "Популярна піцерія з дровʼяною піччю, неаполітанським тістом та щедрими топінгами.",
     "desc_en": "Popular pizzeria with a wood-fired oven, Neapolitan dough and generous toppings.",
     "desc_ru": "Популярная пиццерия с дровяной печью, неаполитанским тестом и щедрыми топпингами."},
    {"id": 10, "name": "Сushimaster", "lat": 50.4495, "lng": 30.5244,
     "cuisine": "Японська", "address": "вул. Хрещатик, 19",
     "url": "https://sushimaster.ua", "hours": [10, 22], "schedule": "all",
     "desc": "Мережевий суші-ресторан з широким меню японської кухні, доступними цінами та швидкою доставкою.",
     "desc_en": "Chain sushi restaurant with an extensive Japanese menu, affordable prices and fast delivery.",
     "desc_ru": "Сетевой суши-ресторан с широким меню японской кухни, доступными ценами и быстрой доставкой."},
    {"id": 11, "name": "Barvy", "lat": 50.4629, "lng": 30.5226,
     "cuisine": "Фʼюжн", "address": "вул. Vozdvyzhenska, 10",
     "url": "", "hours": [11, 23], "schedule": "all",
     "desc": "Арт-ресторан із фʼюжн-кухнею, яскравим дизайном та регулярними виставками сучасного мистецтва.",
     "desc_en": "Art restaurant with fusion cuisine, vibrant design and regular contemporary art exhibitions.",
     "desc_ru": "Арт-ресторан с фьюжн-кухней, ярким дизайном и регулярными выставками современного искусства."},
    {"id": 12, "name": "Piel'meni Project", "lat": 50.4351, "lng": 30.5165,
     "cuisine": "Слов'янська", "address": "вул. Велика Васильківська, 90",
     "url": "", "hours": [10, 22], "schedule": "all",
     "desc": "Концептуальний ресторан з понад 20 видами пельменів, вареників та мантів за рецептами різних слов'янських народів.",
     "desc_en": "Concept restaurant with 20+ types of dumplings and varenyky following recipes from various Slavic peoples.",
     "desc_ru": "Концептуальный ресторан с более чем 20 видами пельменей, вареников и мантов по рецептам разных славянских народов."},
    {"id": 13, "name": "O'Panas", "lat": 50.4571, "lng": 30.5299,
     "cuisine": "Українська", "address": "вул. Михайлівська, 22/3",
     "url": "", "hours": [11, 23], "schedule": "all",
     "desc": "Стилізований ресторан у козацькому дусі з борщем, варениками та горілчаною картою.",
     "desc_en": "Styled restaurant in Cossack spirit with borscht, varenyky and an extensive vodka menu.",
     "desc_ru": "Стилизованный ресторан в казацком духе с борщом, варениками и обширной картой горилки."},
    {"id": 14, "name": "Arena Bar & Grill", "lat": 50.4331, "lng": 30.5220,
     "cuisine": "Гриль", "address": "вул. Велика Васильківська, 120",
     "url": "", "hours": [11, 23], "schedule": "all",
     "desc": "Спортивний бар та гриль — трансляції матчів, стейки на грилі та великий вибір бургерів.",
     "desc_en": "Sports bar and grill — live match screenings, grilled steaks and a wide selection of burgers.",
     "desc_ru": "Спортивный бар и гриль — трансляции матчей, стейки на гриле и большой выбор бургеров."},
    {"id": 15, "name": "Ribs & Beer", "lat": 50.4415, "lng": 30.5178,
     "cuisine": "Гриль / Пиво", "address": "пл. Перемоги, 1",
     "url": "", "hours": [12, 23], "schedule": "all",
     "desc": "Ресторан для любителів ребер та пива — соковиті свинячі ребра на грилі та 16 сортів крафтового пива на кранах.",
     "desc_en": "A rib and beer lover's paradise — juicy grilled pork ribs and 16 craft beers on tap.",
     "desc_ru": "Ресторан для любителей рёбер и пива — сочные свиные рёбра на гриле и 16 сортов крафтового пива на кранах."},
    {"id": 16, "name": "Golden Gate", "lat": 50.4503, "lng": 30.5135,
     "cuisine": "Паб / Гриль", "address": "вул. Volodymyrska, 40а",
     "url": "", "hours": [10, 23], "schedule": "all",
     "desc": "Класичний ірландський паб із живою музикою щовечора, імпортним пивом та грилем.",
     "desc_en": "Classic Irish pub with live music every evening, imported beer and a grill.",
     "desc_ru": "Классический ирландский паб с живой музыкой каждый вечер, импортным пивом и грилем."},
    {"id": 17, "name": "Hibachi", "lat": 50.4559, "lng": 30.5311,
     "cuisine": "Японська", "address": "вул. Мала Житомирська, 3",
     "url": "", "hours": [12, 23], "schedule": "all",
     "desc": "Ресторан з японським грилем теппаньяки — шеф-кухар готує прямо за вашим столом у видовищному стилі.",
     "desc_en": "Japanese teppanyaki grill restaurant — the chef cooks right at your table in a spectacular show-style.",
     "desc_ru": "Ресторан с японским грилем теппаньяки — шеф-повар готовит прямо за вашим столом в эффектном стиле."},
    {"id": 18, "name": "Twins", "lat": 50.4486, "lng": 30.5258,
     "cuisine": "Сучасна", "address": "вул. Хрещатик, 25",
     "url": "", "hours": [11, 23], "schedule": "all",
     "desc": "Сучасний ресторан від шеф-кухарів-близнюків з авторськими стравами, сезонним меню та великою винною картою.",
     "desc_en": "Modern restaurant by twin chefs with signature dishes, seasonal menu and an extensive wine list.",
     "desc_ru": "Современный ресторан от шеф-поваров-близнецов с авторскими блюдами, сезонным меню и большой винной картой."},
    {"id": 19, "name": "Pizzeria Napule", "lat": 50.4462, "lng": 30.5140,
     "cuisine": "Неаполітанська піца", "address": "вул. Baseina, 5",
     "url": "", "hours": [10, 22], "schedule": "mon-sat",
     "desc": "Автентична неаполітанська піцерія — тісто на заквасці, томати Сан-Марцано та моцарела фіор ді латте.",
     "desc_en": "Authentic Neapolitan pizzeria — sourdough crust, San Marzano tomatoes and fior di latte mozzarella.",
     "desc_ru": "Аутентичная неаполитанская пиццерия — тесто на закваске, томаты Сан-Марцано и моцарелла фиор ди латте."},
    {"id": 20, "name": "Bonsai Sushi", "lat": 50.4320, "lng": 30.5191,
     "cuisine": "Японська", "address": "вул. Велика Васильківська, 143",
     "url": "", "hours": [10, 22], "schedule": "all",
     "desc": "Суші-бар з преміальними інгредієнтами, церемонією чаю та медитативною атмосферою японського саду.",
     "desc_en": "Sushi bar with premium ingredients, a tea ceremony and the meditative atmosphere of a Japanese garden.",
     "desc_ru": "Суши-бар с премиальными ингредиентами, чайной церемонией и медитативной атмосферой японского сада."},
]


def get_resto(rid):
    return next((r for r in RESTAURANTS if r["id"] == rid), None)
